Artist.create( name: "Queens of the Stone Age", bio:"Queens of the Stone Age is an American rock band from Palm Desert, California, United States, formed in 1996. The band's line-up includes founder Josh Homme (lead vocals, guitar, piano), alongside longtime members Troy Van Leeuwen (guitar, lap steel, keyboard, percussion, backing vocals), Michael Shuman (bass guitar, keyboard, backing vocals), Dean Fertita (keyboards, guitar, percussion, backing vocals), and recent addition Jon Theodore (drums, percussion).
Formed after the dissolution of Homme's previous band, Kyuss, Queens of the Stone Age developed a style of riff-oriented, heavy rock music. Their sound has since evolved to incorporate a variety of different styles and influences, including working with ZZ Top member Billy Gibbons and steady contributor Mark Lanegan.", song: "Go with the Flow", album: "Songs for the Deaf", year: 2002)
Artist.create( name: "Faith No More" , bio: "Faith No More is an American rock band from San Francisco, California, formed in 1979. Before settling on their current moniker in 1983, the band performed under the names Sharp Young Men and later Faith No Man.Bassist Billy Gould, keyboardist Roddy Bottum and drummer Mike Bordin are the longest remaining members of the band, having been involved with Faith No More since its inception. The band underwent several lineup changes early in their career, along with some major changes later on. The current lineup of Faith No More consists of Gould, Bottum, Bordin, guitarist Jon Hudson, and vocalist Mike Patton.
After releasing six albums, Faith No More officially announced their breakup on April 20, 1998. They have since reunited, embarked on The Second Coming Tour from 2009–2012, and released their seventh studio album, Sol Invictus, in May 2015.", song:"Digging the Grave", album: "King for a Day... Fool for a Lifetime", year: 1995)



Song.create( name: "Go with the Flow", album: "Songs for the Deaf", year: 2002)
Song.create( name: "Digging the Grave ", album: "King for a Day... Fool for a Lifetime", year: 1995)
